#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor2,          armright,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightmotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          armleft,       tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lib-command.h"

task main()
{
	initializeMotors();

		//03/02/19 3:04 PM Changed from 390 to 400
	moveArmMotors(ARM_UP, 400, 50);

	moveLeft(240, 100);

	moveBaseMotors(MOVE_FORWARD, 425, 100);

	moveArmMotors(ARM_UP, 75, 50);

	moveBaseMotors(MOVE_BACKWARD, -400, 100);

	moveLeft(375, 100); //350 400

	moveBaseMotors(MOVE_FORWARD, 680, 100); //800

	moveRight(475, 100);//470

	moveBaseMotors(MOVE_FORWARD, 615, 100);

	moveLeft(70, 80); //250 //150

	moveBaseMotors(MOVE_FORWARD, 675, 100); //600

		//3:04 PM Changed from 765 to 650
	moveBaseMotors(MOVE_BACKWARD, 650, 100); //810

	//3:04 PM Changed from 400 to 350
	moveRight(400, 100);

	//3:04 PM Changed from 325 to 190
	moveBaseMotors(MOVE_FORWARD, 190, 100); //225

	moveLeft(625, 100);

	moveBaseMotors(MOVE_FORWARD, 270, 100); //315

	moveBaseMotors(MOVE_BACKWARD, 130, 100);

	stackLeftYellowHub();
}
