#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor2,          armright,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightmotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          armleft,       tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lib-hang.h"

task main()
{
	initializeMotors();

	moveArm(ARM_UP, 60, 800);
	move(TURN_LEFT, 80, 500);
	move(TURN_RIGHT, 65, 500);

	move(MOVE_FORWARD, 100, 1400);
	stopDriveTerrainMotors();
	moveArmDown(100, 5000);
	sleep(15000);
}
