#pragma config(Motor,  motor1,          leftMotor,     tmotorVexIQ, PIDControl, reversed, driveLeft, encoder)
#pragma config(Motor,  motor2,          armright,      tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor7,          rightmotor,    tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor8,          armleft,       tmotorVexIQ, PIDControl, reversed, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "lib-command.h"
task main()
{
	initializeMotors();

	/*@@@ 001. Move Left @@@*/
	moveMotorTarget(rightmotor, 230, 100);
	waitUntilMotorStop(rightmotor);
	resetMotorEncoder(rightmotor);

	/*@@@ 002. Raise arms @@@*/
	moveMotorTarget(armleft, 384, 100);
	moveMotorTarget(armright, 384, 100);
	waitUntilMotorStop(armleft);
	waitUntilMotorStop(armright);

	/*@@@ 003. Move forward towards yellow hub @@@*/
	moveMotorTarget(leftMotor, 383, 60);
	moveMotorTarget(rightmotor, 383, 60);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightmotor);
	wait1Msec(500);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightmotor);

	/*@@@ 004. Raise arms to pick up yellow hub @@@*/
	moveMotorTarget(armleft, 75, 30);
	moveMotorTarget(armright, 75, 30);
	waitUntilMotorStop(armleft);
	waitUntilMotorStop(armright);
	resetMotorEncoder(armleft);
	resetMotorEncoder(armright);

	/*@@@ 005. Move back with the yellow hub @@@*/
	moveMotorTarget(leftMotor, -480, 75);
	moveMotorTarget(rightmotor, -480, 75);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightmotor);
	wait1Msec(500);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightmotor);

	/*@@@ 001. Move Left @@@*/
	moveMotorTarget(leftMotor, 600, 100);
	waitUntilMotorStop(leftMotor);
	resetMotorEncoder(leftMotor);

	/*@@@ 005. Move back with the yellow hub @@@*/
	moveMotorTarget(leftMotor, -480, 85);
	moveMotorTarget(rightmotor, -480, 85);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightmotor);
	wait1Msec(500);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightmotor);

	moveMotorTarget(leftMotor, 250, 100);
	waitUntilMotorStop(leftMotor);
	resetMotorEncoder(leftMotor);

	/*@@@ 003. Move forward towards yellow hub @@@*/
	moveMotorTarget(leftMotor, 2150, 100);
	moveMotorTarget(rightmotor, 2150, 100);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightmotor);
	wait1Msec(500);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightmotor);

	motor[armleft] = -100;
	motor[armright] = -100;
	wait1Msec(500);

	moveMotorTarget(leftMotor, 300, 120);
	waitUntilMotorStop(leftMotor);
	resetMotorEncoder(leftMotor);


	moveMotorTarget(leftMotor, -500, 75);
	moveMotorTarget(rightmotor, -500, 75);
	waitUntilMotorStop(leftMotor);
	waitUntilMotorStop(rightmotor);
	wait1Msec(500);
	resetMotorEncoder(leftMotor);
	resetMotorEncoder(rightmotor);
}
